### ISSUE TITLE
White theme scrollbar in the Chrome

### ISSUE THREAD

**Issue by davidus27** [amillman/charcoal#4]
The scrollbar is white in the Google Chrome.

## Possible solution

Add `color-scheme` attribute to the root in `styles/themes_v2.less`
For example:
```css
:root {
  color-scheme: dark;
}
```
